# Generated by Django 2.2.2 on 2019-07-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.CharField(max_length=40),
        ),
    ]
