# Generated by Django 2.2.2 on 2019-07-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190710_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
