# Generated by Django 2.2.2 on 2019-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='pub_date',
            field=models.CharField(max_length=40),
        ),
    ]
