# Generated by Django 2.2.2 on 2019-08-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190712_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_main',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
