# Generated by Django 2.2.2 on 2019-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20190824_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_main',
        ),
        migrations.AddField(
            model_name='post',
            name='is_meta',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
